imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    csrf_protection: ~
    default_locale:  "%locale%"
    #esi:             ~
    form:            ~
    fragments:       ~
    http_method_override: true
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    secret:          "%secret%"
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    translator:
        fallback: "%locale%"
    validation:
        enabled: true
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    trusted_hosts:   ~
    trusted_proxies: ~

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Propel Configuration
propel:
    dbal:
        driver:   "%database_driver%"
        user:     "%database_user%"
        password: "%database_password%"
        dsn:      "%database_driver%:host=%database_host%;dbname=%database_name%;%database_charset%"
        options:  {}
        attributes: {}
    build-properties:
        propel.mysql.tableType: "InnoDB"

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    encryption: "%mailer_encryption%"
    port:       "%mailer_port%"
    auth_mode:  "%mailer_auth_mode%"

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
