imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    csrf_protection: ~
    default_locale:  "%locale%"
    #esi:             ~
    form:            ~
    fragments:       ~
    http_method_override: true
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    secret:          "%secret%"
    session:
        handler_id:         session.handler.pdo
    translator:
        fallback: "%locale%"
    validation:
        enabled: true
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    trusted_hosts:   ~
    trusted_proxies: ~

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# FOSUser configuration
fos_user:
    db_driver:          propel
    firewall_name:      main
    user_class:         FOS\UserBundle\Propel\User
    use_listener:       false
    service:
        mailer:         fos_user.mailer.twig_swift

# Propel Configuration
propel:
    dbal:
        driver:   "%database_driver%"
        user:     "%database_user%"
        password: "%database_password%"
        dsn:      "%database_driver%:host=%database_host%;dbname=%database_name%;%database_charset%"
        options:  {}
        attributes: {}
    build-properties:
        propel.mysql.tableType: "InnoDB"

# SensioFrameworkExtra configuration
sensio_framework_extra:
    router:  { annotations: true }
    request: { converters: true }
    view:    { annotations: true }
    cache:   { annotations: true }

services:
    pdo:
        class:          PDO
        arguments:
            dsn:        "mysql:dbname=%database_name%"
            user:       "%database_user%"
            password:   "%database_password%"
        calls:
            - [setAttribute, [3, 2]] # See https://github.com/symfony/symfony/issues/8095

    session.handler.pdo:
        class:          Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments:
            - @pdo
            -
                db_table:       session
                db_id_col:      session_id
                db_data_col:    session_data
                db_time_col:    session_time

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: "twig.extension" }

    twig.extension.debug:
        class:  Twig_Extension_Debug
        tags:
            - { name: "twig.extension" }

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    encryption: "%mailer_encryption%"
    port:       "%mailer_port%"
    auth_mode:  "%mailer_auth_mode%"

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
